name: Update release PR or publish GitHub release

on:
  push:
    branches:
      - master

concurrency: commits-to-master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Inject npm workspaces
        run: |
          jq '.workspaces=["renterd","hostd","walletd"]' package.json > package.json.tmp
          mv package.json.tmp package.json
      - name: Update release pull request or publish
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit: 'chore: release packages'
          publish: bun run publish
          version: bun run version
